# Generated by Django 5.2 on 2025-05-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweekapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
